<%page args="page"/>

// Instance the tour
window.tutorial = new Tour({
  framework: "bootstrap4",
  steps: [
      {
    element: ".card-header h1",
    title: "Aim",
    content: '<p>Given a library of <i>L</i> sequences generated by random recombination of two near-identical genes differing at only a small number of known nucleotide (or amino acid) positions, we wish to calculate the expected number of distinct sequences in the library. (Typically assuming the mean number of crossovers per sequence <i>m</i> &lt; 0.1 &#xD7; sequence length <i>N</i>).</p>',
    placement: 'bottom',
    },
  {
    element: "#driver_library_size",
    title: "Library size",
    content: 'As with other tools, the number, or the extrapolated number of variants (not the cell count after grow up)',
    placement: 'bottom'
  },{
    element: "#driver_length",
    title: "Sequence length",
    content: 'Can be either in nucleotides or amino acids. This is mandatory if crossover location are given',
    placement: 'left'
  },{
    element: "#driver_xtrue",
    title: "Sequence length",
    content: 'Specify whether the crossovers are the observed ones or all crossovers.'
  },{
    element: "#driver_mode",
    title: "Mode",
    content: 'Specify whether to input the two sequences, or the observed crossover points.'
  }
  ],
    backdrop: true,
    orphan: true
});


// Initialize the tour
tutorial.init();

$('#tour').click(function () {
    tutorial.restart();
    // Start the tour
    //tutorial.start();
});