<div id="diver_intro">
 <h3>Description</h3>
<p>Given a library of <i>L</i> sequences generated by random recombination
    of two near-identical genes differing at only a small number of known nucleotide
    (or amino acid) positions, we wish to calculate the expected number of
    distinct sequences in the library. (Typically assuming the mean number
    of crossovers per sequence <i>m</i> &lt; 0.1 &#xD7; sequence length <i>N</i>).</p>
</div>
<h3>Example</h3>
<%include file="driver_example.mako" args="page=page"/>

<h3>Caveats</h3>
<%include file="driver_caveats.mako" args="page=page"/>